---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - role: clickhouse
- name: Install Vector
  hosts: vector
  roles:
    - role: vector
- name: Install Lighthouse
  hosts: lighthouse
  roles:
    - role: lighthouse
